CREATE TABLE Buys(P_id Integer NOT NULL, Pres_id Integer NOT NULL, Drug_id Integer NOT NULL, PRIMARY KEY(P_id, Pres_id, Drug_id), FOREIGN KEY (P_id) REFERENCES Patient(P_id), FOREIGN KEY (Pres_id) REFERENCES Prescription(Pres_id), FOREIGN KEY (Drug_id) REFERENCES DrugStore(Drug_id));
CREATE TABLE Takes(Test_id Integer NOT NULL, P_id Integer NOT NULL, Pres_id Integer NOT NULL, DateOfTest date default (current_date) not null, Timeoftest time default (current_time) NOT NULL, result jsonb,PRIMARY KEY(Test_id, P_id, Pres_id), FOREIGN KEY (Test_id) REFERENCES Test(Test_id), FOREIGN KEY (P_id) REFERENCES Patient(P_id), FOREIGN KEY (Pres_id) REFERENCES Prescription(Pres_id));
CREATE TABLE Prescribes(P_id Integer NOT NULL, Dr_id Integer NOT NULL, Pres_id Integer NOT NULL, PRIMARY KEY(P_id, Dr_id, Pres_id), FOREIGN KEY (P_id) REFERENCES Patient(P_id), FOREIGN KEY (Dr_id) REFERENCES Doctor(Dr_id), FOREIGN KEY (Pres_id) REFERENCES Prescription(Pres_id));
CREATE TABLE ReportTo(N_id Integer NOT NULL, Dr_id Integer NOT NULL, PRIMARY KEY(N_id, Dr_id), FOREIGN KEY (N_id) REFERENCES Nurse(N_id), FOREIGN KEY (Dr_id) REFERENCES Doctor(Dr_id));
CREATE TABLE Drug_Prod(Prod_id Integer NOT NULL, Drug_id Integer NOT NULL, Name varchar(20) NOT NULL, Cost numeric(5,2) NOT NULL check (Cost >=0), Quantity Integer NOT NULL check (Quantity >= 0),PRIMARY KEY(Drug_id, Prod_id), FOREIGN KEY (Drug_id) REFERENCES DrugStore(Drug_id), FOREIGN KEY (Prod_id) REFERENCES Producer(Prod_id));
CREATE TABLE Worksin(N_id Integer NOT NULL, A_id Integer NOT NULL, Shiftstart time NOT NULL, Shiftend time NOT NULL,Available varchar(3) check (Available in ('Yes', 'No')), PRIMARY KEY(N_id, A_id), FOREIGN KEY (N_id) REFERENCES Nurse(N_id), FOREIGN KEY (A_id) REFERENCES NurseAssignment(A_id));
create table BelongsTo (Dr_id Integer Not null, Dept_id Integer Not null, Foreign Key(Dr_id) references Doctor(Dr_id), Foreign Key(Dept_id) references Department(Dept_id), Primary Key(Dr_id, Dept_id));
create table isOf (Op_id Integer Not null, Dept_id Integer Not null, Foreign Key(Op_id) references Operations(Op_id), Foreign Key(Dept_id) references Department(Dept_id), Primary Key(Op_id, Dept_id));    
create table TakesAppoints(P_id Integer Not null, Dr_id Integer Not null, DateOfApp date default(current_date) not null , symptoms varchar(50) [], TimeofApp time default (current_time) NOT NULL, Fees Integer default (500) NOT NULL ,Foreign Key(P_id) references Patient(P_id), Foreign Key(Dr_id) references Doctor(Dr_id), Primary Key(P_id, Dr_id, DateOfApp));
create table OT (Pres_id Integer Not null, Dr_id Integer NOT NULL,P_id Integer Not null, Op_id Integer Not null, DateOfOp date not null, RoomNumber Integer not null, result jsonb,Foreign Key(Pres_id) references Prescription(Pres_id), Foreign Key(P_id) references Patient(P_id), Foreign Key(Op_id) references Operations(Op_id), Primary Key(Pres_id, P_id, Op_id), Foreign Key(Dr_id) references Doctor(Dr_id));

